### ISSUE TITLE
Configuration Server controls

### ISSUE THREAD

**Issue by michal-narajowski** [NordicSemiconductor/Android-nRF-Mesh-Library#18] opened 2018-06-28 12:50 UTC
**Describe the solution you'd like**
I want to be able to control Configuration Server settings of a Mesh node from the app.

**Comment by POHakansson** [comment] 2018-06-28 12:57
I too would like to be able to control TTL and relay status from the app :+1:

**Comment by roshanrajaratnam** [comment] 2018-09-18 12:39
Duplicate of #32

**Closed by roshanrajaratnam** 2018-09-18 12:39 UTC
Labels: enhancement
