### ISSUE TITLE
ConfigRelaySet

### ISSUE THREAD

**Issue by WangManAndroid** [NordicSemiconductor/Android-nRF-Mesh-Library#81] opened 2018-10-25 04:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by roshanrajaratnam** [comment] 2018-10-25 05:48
@WangManAndroid Thanks for sending this feature request, but don't close after openning one unless you don't want it ;) I'll re-open it again. Duplicate of #32

**Comment by WangManAndroid** [comment] 2018-10-25 07:49
hao to make a file for ConfigRelaySet  function?

**Comment by kcjian** [comment] 2018-10-30 10:40
`package no.nordicsemi.android.meshprovisioner.configuration;


import android.content.Context;
import android.util.Log;

import no.nordicsemi.android.meshprovisioner.InternalTransportCallbacks;
import no.nordicsemi.android.meshprovisioner.MeshConfigurationStatusCallbacks;
import no.nordicsemi.android.meshprovisioner.messages.AccessMessage;
import no.nordicsemi.android.meshprovisioner.messages.ControlMessage;
import no.nordicsemi.android.meshprovisioner.opcodes.ConfigMessageOpCodes;
import no.nordicsemi.android.meshprovisioner.utils.MeshParserUtils;

public class ConfigRelaySet extends ConfigMessage {


    private static final String TAG = ConfigRelaySet.class.getSimpleName();

    private final int mAszmic;
    private int relay,relayTransmit;

    public ConfigRelaySet(final Context context, final ProvisionedMeshNode provisionedMeshNode, final boolean aszmic,
                          final InternalTransportCallbacks mInternalTransportCallbacks,
                          final MeshConfigurationStatusCallbacks meshConfigurationStatusCallbacks, int relay, int relayTransmit)  {
        super(context, provisionedMeshNode);
        this.mAszmic = aszmic ? 1 : 0;
        this.mInternalTransportCallbacks = mInternalTransportCallbacks;
        this.mConfigStatusCallbacks = meshConfigurationStatusCallbacks;
        this.relay=relay;
        this.relayTransmit=relayTransmit;
        createAccessMessage();
    }

    @Override
    public MessageState getState() {
        return MessageState.CONFIG_RELAY_SET;
    }

    /**
     * Creates the access message to be sent to the node
     */
    private void createAccessMessage() {
        final byte[] key = mProvisionedMeshNode.getDeviceKey();
        int akf = 0;
        int aid = 0;
        byte[] parameters=new byte[2];
        parameters[0]= (byte) relay;
        parameters[1]= (byte) (byte) (relayTransmit);

        final AccessMessage accessMessage = mMeshTransport.createMeshMessage(mProvisionedMeshNode, mSrc, key, akf, aid, mAszmic,
                ConfigMessageOpCodes.CONFIG_RELAY_SET, parameters);
        mPayloads.putAll(accessMessage.getNetworkPdu());
    }

    /**
     * Starts sending the mesh pdu
     */
    public void executeSend() {
        if (!mPayloads.isEmpty()) {
            for (int i = 0; i < mPayloads.size(); i++) {
                mInternalTransportCallbacks.sendPdu(mProvisionedMeshNode, mPayloads.get(i));
            }

//            if (mConfigStatusCallbacks != null)
//                mConfigStatusCallbacks.onMeshNodeResetSent(mProvisionedMeshNode);
        }
    }

    @Override
    public void sendSegmentAcknowledgementMessage(final ControlMessage controlMessage) {
        final ControlMessage message = mMeshTransport.createSegmentBlockAcknowledgementMessage(controlMessage);
        Log.v(TAG, "Sending acknowledgement: " + MeshParserUtils.bytesToHex(message.getNetworkPdu().get(0), false));
        mInternalTransportCallbacks.sendPdu(mProvisionedMeshNode, message.getNetworkPdu().get(0));
        mConfigStatusCallbacks.onBlockAcknowledgementSent(mProvisionedMeshNode);
    }
}
`

**Comment by roshanrajaratnam** [comment] 2018-10-30 12:39
@kcjian Thanks for this :+1:

 I would really appreciate if you could send this as pull request. This way I can make release it as a part of the library. 
Thanks again!

**Comment by roshanrajaratnam** [comment] 2018-12-12 07:51
Closing in favor of #32

**Closed by roshanrajaratnam** 2018-12-12 07:51 UTC
Labels: duplicate
