### ISSUE TITLE
Segmentation feedback of acknowledged msg is mostly failing when sent to non-proxy device

### ISSUE THREAD

**Issue by R0m4in-dooz** [NordicSemiconductor/Android-nRF-Mesh-Library#426] opened 2021-05-07 15:05 UTC
---

**Describe the bug**
As title states, when sending **segmented** acknowledged messages to **non-proxy** devices, it is too often failing to construct back the Status.

**To Reproduce**
1. Provision at least 2 nodes
2. Connect to proxy
3. Send either `CompositionDataGet`, `ConfigModelPublicationSet`, or any msg that would result in segmented answer to the device that is not the proxy
4. Witness the library failing to construct the Status msg -- it can totally fail or will pass it once a retransmission from the device is done

**Expected behavior**
The library is able to construct the Status as soon as all feedback segments has been received (eg. SEG 0 == SEG N), and the non-proxy device should not have to retransmit at this point (?).

**Platform details:**
 - Device: any
 - OS: Android 9 and above
 - Library Version: 3.1.5
 - Mesh SDK: 4.0
 - Chipset: nrf52840 xxAA
 - MTU size: 66

**Logs / Screenshots**
I spent some time to build enough material for you. I hope it will be enough to spot any bug, or give us hint on why this behavior.

- `CompositionDataGet` :
[compositiondataget_OK.log](https://drive.google.com/file/d/1lZXQNnc-6j5CvCbhTsNgTHKgD8WdRgQq/view?usp=sharing)
[compositiondataget_KO.log](https://drive.google.com/file/d/1Pd6_pQtbyY5OJUGfOCA87Uf---iHyRqF/view?usp=sharing)
[compositiondataget_KO_2.log](https://drive.google.com/file/d/1FZGDGjz4Bs7Zizqk3V0vnqWhsvPedbgz/view?usp=sharing)

- `ConfigModelPublicationSet` :
[configmodelpublicationset_OK.log](https://drive.google.com/file/d/1oUybonH02jwjgH7NCgbSI_vhxSWC3Of7/view?usp=sharing)
[configmodelpublicationset_KO.log](https://drive.google.com/file/d/1gk7MK0ubdHHYYI4urmAqC6I0vTiQpLlW/view?usp=sharing)
[configmodelpublicationset_KO_2.log](https://drive.google.com/file/d/1nMIkQc9OjD7qICnbng84M_g5zYGCLzYU/view?usp=sharing)
[configmodelpublicationset_full_KO.log](https://drive.google.com/file/d/1LfSRsSkjnp4vP57b1glnZiwHPti3hfx0/view?usp=sharing)

- Custom `ApplicationMessage` aka `MagicLevelSet` :
[custom_ApplicationMessage_OK.log](https://drive.google.com/file/d/1Y0Pu_FFGQTAV0LvgNl5kWGOe0AsBnRyZ/view?usp=sharing)
[custom_ApplicationMessage_KO.log](https://drive.google.com/file/d/1kJhjrKleb4nSkUmiAGj_xxI8kWmZvCyl/view?usp=sharing)
[custom_ApplicationMessage_KO_2.log](https://drive.google.com/file/d/1RsM3K_3_39pxx20wKgC-6hWVlm6rhe2K/view?usp=sharing)
[custom_ApplicationMessage_full_KO.log](https://drive.google.com/file/d/1f2HjJ5A0nwMqf8NJ23hKEHe4mnNX1lr-/view?usp=sharing)

_log files suffixed with `OK`_ --> expected behavior
_log files suffixed with `KO`_ --> unexpected behavior: all segments received from device but no Status is being constructed. But we have it once the device is retransmitting some segments
_log files suffixed with `full_KO`_ --> unexpected behavior: all segments received from device but no Status is being constructed. The device seems to have received every acknowledgements as it is not retransmitting

Unfortunately, this behavior is even more problematic in our commercial application as we have implemented a FIFO for such msg with auto-retry mechanism. Meaning this kind of msg is in a FIFO, when sending a cmd, we wait for feedback and retry every 2.5 sec (retried 2 times). The success rate is below 15% because of this problem and it makes the app unusable for a lot of our features. If we increase the retry timer to 5-6sec, the success rate raises to ~60%, but it is still not enough, and is not acceptable for our customers. We may force proxy connection to raise success rate to 95%, but it is not acceptable for most features that need these segmented feedbacks, and moreover it's blocking the power of mesh n/w.

**Comment by roshanrajaratnam** [comment] 2021-05-10 07:31
Hi Rom4in thanks for the detailed report. I will try to take a look at this to see where the issue might be. In the mean time could you check if you are having the same problem on version 2.4.1?

**Comment by R0m4in-dooz** [comment] 2021-05-10 07:55
I tried to make code comparison between 3.1.5 and 2.3.0, but too much changes 😅 And I don't really know where to look in the codebase, except lower transport layer changes that seems to be ok

**Comment by R0m4in-dooz** [comment] 2021-05-14 10:27
Hello @roshanrajaratnam :) any updates ?

**Comment by roshanrajaratnam** [comment] 2021-05-14 17:30
Hey sorry, been busy with some other tasks. Unfortunately i won't be back to work until Tuesday due to national holidays in Norway. I'll try to take a look at this next week!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by roshanrajaratnam** [comment] 2021-05-19 16:56
@R0m4in-dooz I have had some training programs yesterday and today so I have not had time yet to look in to your issue. I will try my best to have a look at this during this week.

**Comment by R0m4in-dooz** [comment] 2021-05-19 16:57
Thanks @roshanrajaratnam, if I may help, with other logs or giving you our custom msg, feel free to ask :)

**Comment by roshanrajaratnam** [comment] 2021-05-19 17:05
Could you also confirm if this is happening with the nRF SDK examples as well?

**Comment by R0m4in-dooz** [comment] 2021-05-19 17:12
If you mean with the nrf example app, yes

**Comment by roshanrajaratnam** [comment] 2021-05-19 17:14
yes example app with the nRF SDK Mesh light/switch examples?

**Comment by R0m4in-dooz** [comment] 2021-05-19 17:17
🤔 i only use our firmwares, based on nrf mesh sdk 4.0

**Comment by R0m4in-dooz** [comment] 2021-05-19 17:18
And I reproduced with publication set msg

**Comment by roshanrajaratnam** [comment] 2021-05-25 21:07
Hi @R0m4in-dooz finally found sometime to look at your issue. However looking at your logs and also after some debugging, I notice that "Message reassembly may not be completed yet!" is logged only when the message is not completed or when the reassembly might be in progress.  If you notice when this is logged not all expected segments are received.

**Comment by R0m4in-dooz** [comment] 2021-05-26 07:55
Yeh, sometimes I expect this log but:
- in compositiondataget_KO.log --> after receiving the 2nd segment which was missing, I indeed get the status, but after that I again receive something. Can you explain ?
```
V/NetworkLayer(19824): TTL for received message: 99
V/NetworkLayer(19824): Dst: 0x0001
V/NetworkLayer(19824): Received a segmented access message from: 0002
V/LowerTransportLayer(19824): SEG O: 2
V/LowerTransportLayer(19824): SEG N: 5
V/LowerTransportLayer(19824): Last SeqAuth value 511
V/LowerTransportLayer(19824): Current SeqAuth value 511
V/LowerTransportLayer(19824): Received segment message count: 6
V/BlockAcknowledgementMessage(19824): Block ack value: 3f
V/BlockAcknowledgementMessage(19824): Block ack: 63
V/BlockAcknowledgementMessage(19824): bit count: 5
V/LowerTransportLayer(19824): Block acknowledgement payload: 07FC0000003F
V/LowerTransportLayer(19824): Creating unsegmented transport control
V/LowerTransportLayer(19824): Unsegmented Lower transport control PDU 0007FC0000003F
V/NetworkLayer(19824): Encryption key: 531F92A8F77688718BB6855F2E35F772
V/NetworkLayer(19824): Privacy key: 73F0C6B5D7B3A2FB34F31A738AF2AD15
V/NetworkLayer(19824): Sequence Number: 0001DF
V/NetworkLayer(19824): Encrypted Network payload: 186235E82A8E46B432454AB4044B4B8822
V/MeshMessageState(19824): Sending acknowledgement: 0019F6A7E69E6BAA186235E82A8E46B432454AB4044B4B8822
D/DoozMeshStatusCallbacks(19824): onBlockAcknowledgementProcessed
V/AccessLayer(19824): Received Access PDU 02005900000000002800070000000400000002000210010000000400021000100310011000000400021000100310011000000300021003100110000001000210
V/ConfigCompositionDataStatus(19824):
[...]
D/fr.dooz.nordic_nrf_mesh.DoozMeshManagerCallbacks(19824): onNetworkUpdated
D/DoozMeshStatusCallbacks(19824): onMeshMessageReceived
D/DoozMeshStatusCallbacks(19824): received a ConfigCompositionDataStatus
V/MeshManagerApi(19824): MeshNetwork pdu sent: 0x0019F6A7E69E6BAA186235E82A8E46B432454AB4044B4B8822
V/MeshManagerApi(19824): Received network pdu: 0x00198C03B0B32F69B8E2E2D9ADC72551ED3F4D82ABC77139EB
V/BaseMeshMessageHandler(19824): TTL for received message: 4
V/BaseMeshMessageHandler(19824): Sequence number of received access message: 479
V/NetworkLayer(19824): TTL for received message: 4
V/NetworkLayer(19824): Received a control message that was not directed to us, so we drop it
V/DefaultNoOperationMessageState(19824): Message reassembly may not be completed yet!
```
- in compositiondataget_KO_2.log --> i never have my status even if all segments have been logged at some point (0,1,3,4,5 and then 1,2,3,5)

- in configmodelpublicationset_KO.log --> I have my status after this is logged : seg 0, seg 1, seg 1, seg 0 and still after the Status is constructed i have the same as compositiondataget_KO.log
- in configmodelpublicationset_KO_2.log -->  I have my status after this is logged : seg 1, seg 0, seg 0, seg 0 seg 1 and still after the Status is constructed i have the same as compositiondataget_KO.log
- in configmodelpublicationset_full_KO.log --> i never have my status even if seg 0 and seg 1 are logged and in the end it says
```
V/MeshMessageState(23796): Sending acknowledgement: 00194768EF39053AB8E96F3BD1CF16713C329C54EA78F30997
D/DoozMeshStatusCallbacks(23796): onBlockAcknowledgementProcessed
V/MeshManagerApi(23796): Received network pdu: 0x00193237EADEAC3D2F3243ED98B1A236B06FF03963AF866DCB
V/BaseMeshMessageHandler(23796): TTL for received message: 4
V/BaseMeshMessageHandler(23796): Sequence number of received access message: 105
V/NetworkLayer(23796): TTL for received message: 4
I/flutter (23796): [NordicReport] received onDataReceived
V/DefaultNoOperationMessageState(23796): Acknowledgement payload: 00000003
V/BlockAcknowledgementMessage(23796): Segment 0 of 1 received by peer
V/BlockAcknowledgementMessage(23796): Segment 1 of 1 received by peer
D/DoozMeshStatusCallbacks(23796): onBlockAcknowledgementReceived
V/MeshManagerApi(23796): MeshNetwork pdu sent: 0x00194768EF39053AB8E96F3BD1CF16713C329C54EA78F30997
V/MeshManagerApi(23796): Received network pdu: 0x001991483AB5612B2FB31BE4E04AE0FD1E1B7FA0AA17BF6647
V/BaseMeshMessageHandler(23796): TTL for received message: 4
V/BaseMeshMessageHandler(23796): Sequence number of received access message: 106
V/NetworkLayer(23796): TTL for received message: 4
V/DefaultNoOperationMessageState(23796): Acknowledgement payload: 00000003
V/BlockAcknowledgementMessage(23796): Segment 0 of 1 received by peer
V/BlockAcknowledgementMessage(23796): Segment 1 of 1 received by peer
D/DoozMeshStatusCallbacks(23796): onBlockAcknowledgementReceived
```
logged all segments received by peer so why no Status ?

I notice that there are a lot of 
```
E/DefaultNoOperationMessageState(23796): Decryption failed in NetworkLayer : mac check in CCM failed
D/DoozMeshStatusCallbacks(23796): onMessageDecryptionFailed
```
maybe it's the cause of the issue ?

**Comment by roshanrajaratnam** [comment] 2021-05-26 09:10
In a mesh network you may receive messages that are not directed to you as they are being relayed, in the network layer we could find out if it was directed to us. There could be instances where you can receive such messages hence we drop it. So the segments you are referring are the once received by the device.

The decryption failure is not something I am able produce using our sample app at all. Have you done any changes? if the decryption fails yes the LowerTransportLayer will timeout eventually.

**Comment by R0m4in-dooz** [comment] 2021-05-26 10:51
> In a mesh network you may receive messages that are not directed to you as they are being relayed, in the network layer we could find out if it was directed to us. There could be instances where you can receive such messages hence we drop it. So the segments you are referring are the once received by the device.

Ok makes sense :)

> The decryption failure is not something I am able produce using our sample app at all. Have you done any changes? if the decryption fails yes the LowerTransportLayer will timeout eventually.

I will try again with sample app and give you those logs if I have it again 👍🏼 but we only added our custom ApplicationMessage on top of 3.1.5 + new build flavor which fallback to your definition (specific flutter bug fix). 
So you don't have any issue to have ConfigModelPublicationSetStatus when it comes from non-proxy device ?

What about composition data log KO_2 and publication set log full_KO ?
You never have this behavior ?

**Comment by roshanrajaratnam** [comment] 2021-05-26 11:20
ok sounds good. I do not see any issues relating to  CompositionDataGet or ConfigModelPublicationSet message sent via proxy or to proxy. Let me know how this goes for you.

**Comment by R0m4in-dooz** [comment] 2021-06-23 14:07
Hello there. Sorry I didn't have time to look into this issue as we have a workaround on prod and I was busy with some other priorities! We may find some time to look for it. But first we will try out the new release 🕺

**Comment by R0m4in-dooz** [comment] 2021-07-06 07:00
Hello ! 
After upgrading to latest release, we still have issues on segmented answers. It is behaving better tho !
I don't have anymore issues on CompositionDataGet, nor our custom 2 segments ApplicationMessage. 
However, for ConfigModelPublicationSet, I still experience troubles to construct Status from segments. I think it has changed behavior and now, I always have these two logs when it fails:
```
D/DoozMeshStatusCallbacks(13381): onBlockAcknowledgementProcessed
E/DefaultNoOperationMessageState(13381): Decryption failed in NetworkLayer : mac check in CCM failed
D/DoozMeshStatusCallbacks(13381): onMessageDecryptionFailed
```
Even if later it has these two logs:
```
V/BlockAcknowledgementMessage(13381): Segment 0 of 1 received by peer
V/BlockAcknowledgementMessage(13381): Segment 1 of 1 received by peer
```

The success rate has increase so it is better, but for pubs it is still not enough and I can't revert our force proxy code workaround.
I feel like our FIFO with auto-retry is messing with your "segment queue", because often, it is constructing the Status some seconds after our retries are done (3x publication set)

**Comment by R0m4in-dooz** [comment] 2021-07-06 07:02
It is still rly better, so thank for your work on low layers :)

**Comment by roshanrajaratnam** [comment] 2021-07-06 07:15
hey again, no problem, does this happen on a custom firmware, could you share it? I am not able to reproduce this on our sdk.

**Comment by R0m4in-dooz** [comment] 2021-07-06 07:19
I will ask our embedded team

**Comment by R0m4in-dooz** [comment] 2021-07-06 07:29
@roshanrajaratnam is roshan.rajaratnam@nordicsemi.no a valid email to receive a Google Drive share link ?

**Comment by roshanrajaratnam** [comment] 2021-07-06 07:44
android-devs@nordicsemi.no

**Comment by R0m4in-dooz** [comment] 2021-07-06 08:01
I just sent the .hex file

**Comment by roshanrajaratnam** [comment] 2021-07-06 08:06
Thanks I just got it, I will take a look at it later during the day. What dk is this built for ?

**Comment by R0m4in-dooz** [comment] 2021-07-06 08:13
This one :)
![compatible_DK](https://user-images.githubusercontent.com/72380352/124565838-bcb33100-de42-11eb-825c-1a523e774017.jpeg)

**Comment by R0m4in-dooz** [comment] 2021-07-12 20:17
Hello ! Any update on the subject?

**Comment by philips77** [comment] 2021-07-14 06:24
Hi, we're all on vacations right now. Please expect some delays in responses in July.

**Comment by R0m4in-dooz** [comment] 2021-12-09 10:26
Hi there !
I see you are closing issues due to inactivity.
This issue is **still there**, and I'm still awaiting support from you guys. I provided a .hex file in beginning of summer and still no feedback but this issue is labelled "awaiting user input" ??
Please notify me if you find any time to try to reproduce the issue with our firmware 😁

**Comment by roshanrajaratnam** [comment] 2021-12-09 11:17
Hi, it was labelled awaiting user input long time ago I guess. I have been busy with some other projects. I will look in to yours ;)

**Comment by roshanrajaratnam** [comment] 2021-12-09 11:44
@R0m4in-dooz could you share your fw again please? Can't seem to find it anymore!

**Comment by R0m4in-dooz** [comment] 2021-12-09 11:47
sure, I may have deleted it 😅 

Still this mail ?
> [android-devs@nordicsemi.no](mailto:android-devs@nordicsemi.no)

**Comment by roshanrajaratnam** [comment] 2021-12-09 11:48
indeed!

**Comment by R0m4in-dooz** [comment] 2021-12-09 11:51
sent 👍

**Comment by roshanrajaratnam** [comment] 2021-12-09 18:36
Hi couple of things here, I find the firmware a bit flaky. Sometimes it provisions and sometimes it doesn't if I disconnect after completing provisioning before going in to configuration. I see this happening only with the debug firmware that you had sent. 

Also I noticed a decryption failure that you have pointed out earlier in our conversation which only seem to happen with your firmware. I have done multiple tests with both our example sdk and the debug firmware you sent and I don't see this happening against the Nordic sdk examples.

Although I notice there is an issue with the proxy node not sending the response/status to acknowledged messages. According to what I see on logs on my end, I get block acks  that all segments are received and it stops there and I don't seem to receive the response over GATT via the proxy node. So this could be related to the issue you are facing. I would recommend creating a ticket on DevZone so that someone from the technical support could provide support on this case.

**Comment by R0m4in-dooz** [comment] 2021-12-10 11:15
Hello ! 
Thank you for your time @roshanrajaratnam !
> I find the firmware a bit flaky

It may be possible that the FW I sent is buggy, we made numerous updates since then 😅 (I sent you firmware from July)
> Also I noticed a decryption failure that you have pointed out earlier in our conversation which only seem to happen with your firmware. I have done multiple tests with both our example sdk and the debug firmware you sent and I don't see this happening against the Nordic sdk examples.

🤔 ok then, if it is only with our firmware I will tell our embedded team to investigate
> Although I notice there is an issue with the proxy node not sending the response/status to acknowledged messages.

Does this means that you indeed see a bug ? But you think it's only with our custom firmware ?
>  I would recommend creating a ticket on DevZone so that someone from the technical support could provide support on this case.

We recently upgraded the Mesh SDK and are in the process of validation now. I will test against these new firmwares and if still there I can indeed think to post a ticket in DevZone...

So for you, nothing is wrong with segmented messages handling in the current library version ? We are on 3.1.6 official release, maybe the dev branch is correcting some issues ? I should check commit history...

**Comment by roshanrajaratnam** [comment] 2021-12-10 11:54
@R0m4in-dooz there was a fix made couple of days ago on #458, but this applies to all segmented messages relating to the sequence number getting reset. The decryption failure in your case has still been the same as pointed out earlier in our conversations. Please test it on your end as well just see if we are on the same page!

**Comment by R0m4in-dooz** [comment] 2021-12-10 13:25
Hello ! 
Thank you for your time @roshanrajaratnam !
> I find the firmware a bit flaky

It may be possible that the FW I sent is buggy, we made numerous updates since then 😅 (I sent you firmware from July)
> Also I noticed a decryption failure that you have pointed out earlier in our conversation which only seem to happen with your firmware. I have done multiple tests with both our example sdk and the debug firmware you sent and I don't see this happening against the Nordic sdk examples.

🤔 ok then, if it is only with our firmware I will tell our embedded team to investigate
> Although I notice there is an issue with the proxy node not sending the response/status to acknowledged messages.

Does this means that you indeed see a bug ? But you think it's only with our custom firmware ?
>  I would recommend creating a ticket on DevZone so that someone from the technical support could provide support on this case.

We recently upgraded the Mesh SDK and are in the process of validation now. I will test against these new firmwares and if still there I can indeed think to post a ticket in DevZone...

So for you, nothing is wrong with segmented messages handling in the current library version ? We are on 3.1.6 official release, maybe the dev branch is correcting some issues ? I should check commit history...

> Please test it on your end as well just see if we are on the same page!

Sure, I'll try to find some time to make new tests against our updated firmwares and against `dev` branch ASAP. Thanks again, I'll let you know how it goes 👍

**Comment by bslisowski** [comment] 2023-01-18 04:47
@R0m4in-dooz was your embedded team able to resolve the issue of the proxy node not sending response messages? I am having the same issue using your flutter plugin for my mobile app and esp32's for nodes.

**Comment by R0m4in-dooz** [comment] 2023-01-18 06:10
Hello @bslisowski ,

Please use our repository to post issues !
Well, unfortunately I am slowly forgotting our adventures on mesh network..if I remember correctly, no we never fixed that bug and could not figure out if it was a firmware problem or a mobile app problem.

Hi @roshanrajaratnam, i guess you can close this one, it was probably a problem on our side 👍

**Comment by bslisowski** [comment] 2023-01-18 19:01
I was going to post an issue on your repository, but I don't think your plugin is the problem since it still persists when using the latest version of the nRF mesh app.

**Comment by roshanrajaratnam** [comment] 2023-01-19 12:13
@bslisowski I would recommend creating an issue on d so that our tech support should be able to help you on this issue.

**Comment by bslisowski** [comment] 2023-01-19 23:08
I believe I found the issue - the placement of the bluetooth antenna on our PCB is interfering with the transmission. I was able to increase the transmission power and the problem is almost completely gone.

**Comment by roshanrajaratnam** [comment] 2023-01-20 07:27
Awesome, I'll close this issue.

**Closed** 2023-01-20 07:27 UTC
Labels: awaiting user input
