### ISSUE TITLE
App fails to provisio. 

### ISSUE THREAD

**Issue by EnMMSegur** [NordicSemiconductor/Android-nRF-Mesh-Library#274] opened 2019-11-19 12:26 UTC
The app fails to provision any node and gets stuck sending the public key.

**Comment by philips77** [comment] 2019-11-20 07:42
I believe this is duplicate of #250. I may now have a way to reproduce this issue here, so I should be able to fix it. It's related to Android BLE Library 2.x and how it handles incoming notifications.

**Closed** 2019-11-20 07:42 UTC
Labels: duplicate
